# Generated by Django 4.2.1 on 2023-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='disease',
            field=models.CharField(max_length=10),
        ),
    ]
