# Generated by Django 4.2.1 on 2023-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=50)),
                ('건수', models.IntegerField()),
                ('조합', models.CharField(max_length=50)),
            ],
        ),
    ]
