# Generated by Django 4.2.1 on 2023-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prohibition_Of_Combination',
            fields=[
                ('제품명A', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('제품명B', models.CharField(max_length=50)),
                ('상세정보', models.CharField(max_length=100)),
                ('업체명A', models.CharField(max_length=50)),
                ('업체명B', models.CharField(max_length=50)),
            ],
        ),
    ]
