# Generated by Django 4.2.1 on 2023-06-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='제품성분코드',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='제품코드',
            field=models.CharField(default='', max_length=100),
        ),
    ]
