# Generated by Django 4.2.1 on 2023-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_prohibition_of_combination_제품성분코드_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prohibition_of_combination',
            name='제품성분코드',
        ),
        migrations.RemoveField(
            model_name='prohibition_of_combination',
            name='제품코드',
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='성분명A',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='성분명B',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='성분코드A',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='성분코드B',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='제품코드A',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prohibition_of_combination',
            name='제품코드B',
            field=models.CharField(default='', max_length=100),
        ),
    ]
