# Generated by Django 4.2.1 on 2023-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='e_pill_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제품명A', models.CharField(max_length=50)),
                ('품목일련번호', models.CharField(max_length=50)),
                ('주성분', models.CharField(max_length=50)),
                ('효능', models.CharField(max_length=50)),
                ('사용법', models.CharField(max_length=50)),
                ('사전지식', models.CharField(max_length=50)),
                ('주의음식', models.CharField(max_length=50)),
                ('이상반응', models.CharField(max_length=50)),
                ('보관법', models.CharField(max_length=50)),
                ('사업자번호', models.CharField(max_length=50)),
                ('url_key', models.CharField(max_length=110)),
            ],
        ),
    ]
