# Generated by Django 4.2.1 on 2023-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_pill_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_pill_info',
            name='url_key',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='보관법',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='사업자번호',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='사용법',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='사전지식',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='이상반응',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='제품명A',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='주성분',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='주의음식',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='품목일련번호',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_pill_info',
            name='효능',
            field=models.CharField(max_length=500),
        ),
    ]
