# Generated by Django 4.2.1 on 2023-06-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('보관법', models.CharField(max_length=50)),
            ],
        ),
    ]
