# Generated by Django 4.2.1 on 2023-06-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='보관법',
        ),
    ]
