# Generated by Django 4.2.1 on 2023-06-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0002_remove_user_info_보관법'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='phone',
        ),
    ]
