# Generated by Django 4.2.1 on 2023-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0003_remove_user_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
