# Generated by Django 4.2.1 on 2023-06-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0004_user_info_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_info",
            old_name="id",
            new_name="user_id",
        ),
    ]
