# Generated by Django 4.2.1 on 2023-06-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0005_rename_id_user_info_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_info",
            old_name="user_id",
            new_name="id",
        ),
    ]
