# Generated by Django 4.0 on 2023-06-12 01:27

from django.db import migrations, models
import userinformation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0006_rename_user_id_user_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(error_messages={'unique': '이미 있는 아이디입니다.'}, max_length=20, unique=True, validators=[userinformation.validators.validate_id_input])),
                ('disease', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('pw', models.CharField(max_length=20, validators=[userinformation.validators.validate_pw_input])),
                ('email', models.EmailField(error_messages={'unique': '이미 등록된 이메일입니다.'}, max_length=254, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13, validators=[userinformation.validators.validate_phone_input])),
            ],
        ),
    ]
