# Generated by Django 4.0 on 2023-06-12 01:59

import datetime
from django.db import migrations, models
import django.utils.timezone
import userinformation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0007_accountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='dt_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='dt_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=1, validators=[userinformation.validators.validate_gender_input]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='has_surgery',
            field=models.BooleanField(default=False),
        ),
    ]
