# Generated by Django 4.0 on 2023-06-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0009_alter_accountinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='password',
            field=models.CharField(default='password1234', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
