# Generated by Django 4.2.1 on 2023-06-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0011_accountinfo_is_staff_alter_accountinfo_has_surgery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinfo",
            name="admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="has_surgery",
            field=models.BooleanField(default=False),
        ),
    ]
