# Generated by Django 4.2.1 on 2023-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0012_alter_accountinfo_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinfo",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
