# Generated by Django 4.2.1 on 2023-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0013_alter_accountinfo_admin_alter_accountinfo_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='user_pill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
