# Generated by Django 4.2.1 on 2023-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0014_accountinfo_user_pill"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinfo",
            name="user_specialnote",
            field=models.CharField(default="", max_length=100),
        ),
    ]
