# Generated by Django 4.2.2 on 2023-06-21 04:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0015_accountinfo_user_specialnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinfo",
            name="disease",
            field=models.CharField(
                max_length=200, 
                default='', 
                blank=True),
        ),
    ]
