# Generated by Django 4.2.2 on 2023-06-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0016_alter_accountinfo_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinfo",
            name="disease",
            field=models.CharField(blank=True, default=[], max_length=200),
        ),
    ]
