# Generated by Django 4.2.2 on 2023-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0019_alter_accountinfo_user_specialnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinfo",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="accountinfo",
            name="pharmacy",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
