# Generated by Django 4.2.2 on 2023-07-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinformation", "0020_accountinfo_license_number_accountinfo_pharmacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
