# Generated by Django 4.2.1 on 2023-06-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinformation', '0004_user_info_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('질문', models.CharField(choices=[('영업시간', '영업시간이 어떻게 되나요?'), ('상품문의', '혹시 의약품도 따로 판매하나요?'), ('기부금문의', '기부하고 싶은데 계좌번호가 어떻게 되나요?')], max_length=100)),
                ('답변', models.CharField(max_length=100)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinformation.user_info')),
            ],
        ),
    ]
