# Generated by Django 4.2.1 on 2023-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_qna_질문'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
