# Generated by Django 4.2.1 on 2023-06-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_qna_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='answer_info',
            field=models.CharField(default='익명', max_length=100),
        ),
    ]
