# Generated by Django 4.2.1 on 2023-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0006_qna_answer_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qna",
            name="질문",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
