# Generated by Django 4.2.1 on 2023-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0007_alter_qna_질문"),
    ]

    operations = [
        migrations.AddField(
            model_name="qna",
            name="answer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="qna",
            name="question",
            field=models.CharField(default="", max_length=100),
        ),
    ]
